output_dir: null
n_workers: 1
debug_mode: false
pth_path: /home/ali/projects/clouds-decoded/model_height_emulator.pth
bands:
- B02
- B03
- B04
- B08
- B11
- B12
window_size:
- 512
- 512
overlap: 256
batch_size: 1
in_channels: 6
device: cuda
