# YAML

SCENE_DIR: /mnt/raid/data/lot-sample-s2-scenes/S2A_MSIL1C_20170119T110351_N0204_R094_T31UDP_20170119T110533.SAFE
THRESHOLD_BAND: 'B03'
STRIDE: 800
HEIGHT_STEP: 200
ALONG_TRACK_RESOLUTION: 1 # pixel size that is used during convolution, in metres
ACROSS_TRACK_RESOLUTION: 10 # pixel size that is used during convolution, in metres
CONVOLVED_SIZE_ALONG_TRACK: 300 # Size that is used in correlation along track. In metres
CONVOLVED_SIZE_ACROSS_TRACK: 300 # Size that is used in correlation along track. In metres
PLOT_WRITETO: 'heights_new.png'
TARGET_FEATURES: 'gradient' # 'gradient' or 'reflectance'. Currently 'reflectance' doesn't work very well. We could also explore more complex features like HoG or SIFT.

N_WORKERS: 4

CLOUDY_THRESH: 1500
MAX_HEIGHT: 16_000