ACROSS_TRACK_RESOLUTION: 10
ALONG_TRACK_RESOLUTION: 10
BANDS:
# - B01
- B02
- B03
- B04
# - B05
# - B07
- B08
# - B8A
CLOUDY_THRESH: 1600
THRESHOLD_BAND: B02
CONVOLVED_SIZE_ACROSS_TRACK: 200
CONVOLVED_SIZE_ALONG_TRACK: 200
HEIGHT_STEP: 100
MAX_HEIGHT: 18000
N_WORKERS: 32
TARGET_FEATURES: reflectance # 'gradient' or 'reflectance', whether to correlate the gradient or the reflectance of the bands
STRIDE: 100
OUTPUT_DIR: /app/out_dir/ATR10
SMOOTHING_MODE: spatial
SPATIAL_SMOOTHING_SIGMA: 100 # Standard deviation of Gaussian kernel for spatial smoothing, in metres
CORRELATION_WEIGHTING: True 