# YAML

SCENE_DIR: /mnt/raid/data/sample-sentinel2-scenes/S2B_MSIL1C_20250104T185019_N0511_R127_T09KVQ_20250104T220125.SAFE
BANDS: ['B02','B03','B01']
THRESHOLD_BAND: 'B03'
STRIDE: 300
HEIGHT_STEP: 500
CONVOLUTION_UPSAMPLING_RESOLUTION: 4
PLOT_WRITETO: 'heights.png'