services:
  cloud-height:
    shm_size: 2g
    build:
      context: .
      dockerfile: dockerfile
    container_name: cloud-height
    volumes:
      # Mount data directory
      # - /mnt/raid/data/s2get:/app/s2get:r
      # Mount data output directory
      - /mnt/raid/data/CTH_emulator_dataset:/app/CTH_emulator_dataset

    environment:
      - PYTHONUNBUFFERED=1 # Ensures real-time logs
      - SCENE_DIR=

    command: >
      echo "${SCENE_DIR}"
      bash -c "source ~/.bashrc && conda activate geoenv && python ./src/main.py --config /app/config.yaml --scene_dir /app/s2get/${SCENE_DIR} --plot --save --log"
