name: geoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal
  - matplotlib>=3.10.7
  - numpy>=2.2.6
  - pyaml>=25.7.0
  - pyproj>=3.7.1
  - rasterio>=1.4.3
  - rtree>=1.4.1
  - scipy>=1.15.3
  - tqdm>=4.67.1
  - libgdal-jp2openjpeg
