output_dir: null
n_workers: 1
debug_mode: false
model_path: /home/ali/projects/clouds-decoded/emulator_model_no_stripping_epoch70.pth
bands:
- B02
- B03
- B04
- B08
- B11
- B12
- B09
- B10
window_size:
- 1024
- 1024
overlap: 512
batch_size: 1
in_channels: 8
device: cuda
